tap "caskroom/cask"
tap "homebrew/versions"

brew "ack"
brew "binutils"
brew "coreutils"
brew "diff-so-fancy"
brew "findutils"
brew "fzf"
brew "git"
brew "gnu-sed", args: ["with-default-names"]
brew "grep"
brew "jq"
brew "lua"
brew "moreutils"
brew "neovim"
brew "openssh"
brew "python3"
brew "readline"
brew "socat"
brew "stow"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "vim", args: ["verride-system-vi"]
brew "wget", args: [ "with-iri" ]
brew "zsh"
brew "zsh-completions"
cask "docker"
cask "flycut"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
cask "kitematic"
cask "pritunl"
cask "slack"
cask "spotify"
cask "zeplin"
