#!/usr/bin/env zsh

fpath=(${DOTFILES}/lib $fpath)
autoload _dotfiles_plugin_enable

usage() {
  echo "USAGE: myscript COMMAND plugin"
  exit 1
}

enable() {
}

install() {
  if [ $# -lt 1 ]; then
    echo "Usage: dotfiles install REMOTE_URL"
  fi

  pushd $HOME/.config/dotfiles/.remote_plugins/
  git clone $1
  popd
}

if [ $# -lt 1 ]; then usage; fi

case "$1" in
  enable)
    shift
    _dotfiles_plugin_enable($ARGV)
    ;;

  install)
    shift
    install $1
    ;;

  *)
    echo "dotfile: Wrong command";
    exit 1;
esac
