#! /usr/local/bin/python
#! /usr/bin/env python
import argparse
import os
import mmap
import imp

current_dir = os.path.dirname(os.path.realpath(__file__))

parser = argparse.ArgumentParser(description='Install DotFiles')
#parser.add_argument('--skip-git',  action='store_true', help='Skip dotfiles for git.')
#parser.add_argument('--skip-ruby', action='store_true', help='Skip dotfiles for ruby.')
#parser.add_argument('--skip-vim',  action='store_true', help='Skip dotfiles for vim.')
parser.add_argument('--macosx',    action='store_true', help='MacOSX version.')
parser.add_argument('-v','--verbose', dest='verbose', action='store_true', help='Verbose mode.')

subparsers = parser.add_subparsers(help='sub-command help')

parser_module = subparsers.add_parser('module', help='a help')
parser_module.add_argument('name', help='Name of module to install')

args = parser.parse_args()

class Logger:
  verbose = False
  def __init__(self, verbose=False):
    self.verbose = verbose

  def log(self, msg):
    if self.verbose:
      print(msg),

logger = Logger(verbose=args.verbose)

class ModuleInstaller:
  @staticmethod
  def install(name):
    home = os.getenv('HOME')
    enabled_path = current_dir + '/modules_enabled/' + name

    if not os.path.exists(enabled_path):
      logger.log("Installing '" + name + "' module...")
      os.symlink(current_dir + '/modules_available/' + name, enabled_path )
      files = os.listdir(enabled_path + '/home/')
      for f in files:
        if not os.path.exists(home + '/' + f ):
          os.symlink(enabled_path + '/home/' + f, home + '/' + f)
        else:
          log("\n'" + f + "' already exists, skipping...")
      logger.log(' done!\n')
    else:
      logger.log("'" + name +"' module already installed, skipping...\n")

class CoreInstaller:
  @staticmethod
  def install(macosx=False):
    home = os.getenv("HOME")
    if macosx:
      bashrc_path = home + '/.bash_profile'
    else:
      bashrc_path = home + '/.bashrc'

    bashrc_file = open(bashrc_path, 'r')
    bashrc = bashrc_file.readlines()
    bashrc_file.close()
    found = False
    for line in bashrc:
      if str('# DOTFILES SOURCE #\n') in line:
        found = True

    if not found:
      with open(bashrc_path, 'a') as f:
        logger.log("Installing CORE...")
        f.write('\n# DOTFILES SOURCE #\n')
        f.write('source ' + current_dir + '/core/lib.bash\n')
        f.write('source ' + current_dir + '/core/bash_profile\n')
        logger.log(" Done!\n")
    else:
      logger.log("CORE already installed, skipping...\n")


print args
CoreInstaller.install(args.macosx)
ModuleInstaller.install(args.name)
