SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#Git completation on bash terminal
source ${DIR}/../GIT/git-completion.bash

# Git configuration
source ${DIR}/git_profile

# PS1 configuration
source ${DIR}/ps1_profile

# RbEnv configuration
source ${DIR}/rbenv_profile

#Export the path variable.
export PATH=${PATH}
